### ISSUE TITLE
Error in muxing

### ISSUE THREAD

**Issue by spacex97** [sheldonkwoodward/pymkv#56]
Hi
I am getting following error on first run when muxing file while second run mux fine. Pls check and suggest how to resolve issue.

> Traceback (most recent call last):
>   File "hotstar.py", line 710, in <module>
>     mkv.mux(outfile)
>   File "C:\Users\Adi\AppData\Local\Programs\Python\Python36\lib\site-packages\pymkv\MKVFile.py", line 261, in mux
>     output_path = expanduser(output_path)
>   File "C:\Users\Adi\AppData\Local\Programs\Python\Python36\lib\ntpath.py", line 312, in expanduser
>     path = os.fspath(path)
> TypeError: expected str, bytes or os.PathLike object, not _io.BufferedWriter

**Comment by spacex97** [comment]
it was variable issue "outfile" which I was using. I changed variable name and it worked fine as outfile was defined earlier also in script.
